var beers = ['하이네켄', '코로나', '스텔라', '카스'];
beers.push('수제맥주', '제주비어');
document.write(beers);
document.write('<hr/>');
document.write('값 추가하기-unshift');
document.write('<p>' + '기존의 값 앞에 추가한다.' + '<p/>');
var beers = ['하이네켄', '코로나', '스텔라', '카스'];
beers.unshift('수제맥주', '제주비어');
document.write(beers);
document.write('<hr/>');
document.write('값 삭제하기-pop');
document.write('<p>' + '기존의 값 뒤에 삭제한다.' + '<p/>');
var beers = ['하이네켄', '코로나', '스텔라', '카스'];
beers.pop();
document.write(beers);
document.write('<hr/>');
document.write('값 삭제하기-shift');
document.write('<p>' + '기존의 값 앞에 삭제한다.' + '<p/>');
var beers = ['하이네켄', '코로나', '스텔라', '카스'];
beers.shift();
document.write(beers);